package com.haoyang.settings.mapper;

import com.haoyang.settings.pojo.DicValue;

import java.util.List;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Aug 08 16:17:42 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Aug 08 16:17:42 CST 2022
     */
    int insert(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Aug 08 16:17:42 CST 2022
     */
    int insertSelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Aug 08 16:17:42 CST 2022
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Aug 08 16:17:42 CST 2022
     */
    int updateByPrimaryKeySelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Mon Aug 08 16:17:42 CST 2022
     */
    int updateByPrimaryKey(DicValue row);

    /**
     * 通过自定义的类型编码查询对应的字典表数据
     * @param typeCode 类型编码
     * @return 对应字典表数据
     */
    List<DicValue> selectDicValueByTypeCode(String typeCode);

    /**
     * 通过id查询对应的字典表数据
     * @param id 字典数据id
     * @return 字典表数据
     */
    DicValue selectDicValueById(String id);
}